Setup:
  ModelDir: models/Tf-exp
  Device: gpu # gpu / cpu
  PytorchSeed: 1893
  Seed: 123146427

ExpDetails:
  Dataset: Parkinsion #  Valid:- Parkinsion, Gender, Parkinsion-mx, Philippine, Emotion
  Network: Transformer # Valid:- Transformer


Datasets:
  Parkinsion:
    MainCSV: data/parkinsion/pd_speech_features.csv
    FeatureDist: data/parkinsion/feature_details.csv
    FeatureImp: data/parkinsion/xgboost_feature_ranking.json
    Split: data/parkinsion/split_details.json
    NumFeatures : 96
    Smote: True
    SmoteSeed: 722152
    K-Fold: 10

  Gender:
    MainCSV: data/Gender/cleaned_gender.csv
    FeatureDist: data/Gender/feature_mapping.json
    FeatureImp: data/Gender/xgboost_feature_ranking.json
    Split: data/Gender/split_details.json
    NumFeatures: 16
    Smote: True
    SmoteSeed: 722152
    K-Fold: 10

  Parkinsion-mx:
    MainCSV: data/parkinsion-mx/train_data.csv
    FeatureDist: data/parkinsion-mx/feature_mapping.json
    FeatureImp: data/parkinsion-mx/xgboost_feature_ranking.json
    Split: data/parkinsion-mx/split_details.json
    NumFeatures: 16
    Smote: True
    SmoteSeed: 722152
    K-Fold: 10

  Philippine:
    MainCSV: data/philippine/cleaned_phillippine.csv
    FeatureDist: data/philippine/feature_stat.json
    FeatureImp: data/philippine/xgboost_feature_ranking.json
    Split: data/philippine/split_details.json
    NumFeatures: 16
    K-Fold: 10

  Emotion:
    MainCSV: data/Emotion/ANAD_Normalized.csv
    FeatureImp: data/Emotion/xgboost_feature_ranking.json
    Split: data/Emotion/split_details.json
    NumFeatures: 16
    Smote: True
    SmoteSeed: 722152
    K-Fold: 10

Networks:
  Transformer:
    EmbeddingDim : 64
    EncoderStack : 6
    AttentionHead : 1
    Dropout : 0.1
    HD-1: 2048
    OutDim: 1

  TransformerGroup:
    EmbeddingDim: 64
    EncoderStack: 6
    AttentionHead: 1
    Dropout: 0.1
    HD-1: 2048
    OutDim: 1
    FeatureSet:
      - Baseline Features
      - Intensity Parameters
      - Formant Frequencies
      - Bandwidth Parameters
      - Vocal Fold
      - MFCC
      - Wavelet Features
      - TQWT Features

  FeatureEmbedMLP:
    EmbeddingDim: 64
    Dropout: 0.1
    HD-1: 2048
    OutDim: 1

  MLP:
    Dropout: 0.1
    HD-1: 2048
    HD-2: 512
    OutDim: 1

  DeepMLP:
    Stack: 6
    Dropout: 0.1
    HD-1: 2048
    HD-2: 512
    OutDim: 1

  ConvModel:
    Conv1: 16
    Conv2: 32
    HD-1: 1024
    HD-2: 512
    OutDim: 1

Train:
  LR: 0.0001
  BatchSize: 32
