# datasets

Exp Details:
  Dataset: Emotion #
  Network: Transformer #


Datasets:
  Parkinsion:
    MainCSV: data/parkinsion/pd_speech_features.csv
    FeatureDist: data/parkinsion/feature_details.csv
    FeatureImp: data/parkinsion/xgboost_feature_ranking.json
    Split: data/parkinsion/split_details.json
    NumFeatures : 96
    Smote: True
    SmoteSeed: 722152

  Gender:
    MainCSV: data/Gender/cleaned_gender.csv
    FeatureDist: data/Gender/feature_mapping.json
    FeatureImp: data/Gender/xgboost_feature_ranking.json
    Split: data/Gender/split_details.json
    NumFeatures: 16
    Smote: True
    SmoteSeed: 722152

  Parkinsion-mx:
    MainCSV: data/parkinsion-mx/train_data.csv
    FeatureDist: data/parkinsion-mx/feature_mapping.json
    FeatureImp: data/parkinsion-mx/xgboost_feature_ranking.json
    Split: data/parkinsion-mx/split_details.json
    NumFeatures: 16
    Smote: True
    SmoteSeed: 722152

  Philippine:
    MainCSV: data/philippine/cleaned_phillippine.csv
    FeatureDist: data/philippine/feature_stat.json
    FeatureImp: data/philippine/xgboost_feature_ranking.json
    Split: data/philippine/split_details.json
    NumFeatures: 16

  Emotion:
    MainCSV: data/Emotion/ANAD_Normalized.csv
    FeatureImp: data/Emotion/xgboost_feature_ranking.json
    Split: data/Emotion/split_details.json
    NumFeatures: 16
    Smote: True
    SmoteSeed: 722152


Default Network:
  EMBEDDING_DIM : 64
  ENCODER_STACK : 6
  ATTENTION_HEAD : 1
  DROPOUT : 0.1


Train:
  LR: 0.0001
  BATCH_SIZE: 32
  SMOTE_SEED : 722152